### ISSUE TITLE
Localazy uses default values for fields that are not selected when downloading other languages 

### ISSUE THREAD

**Issue by kingkong0828** [localazy/strapi-plugin#32] opened 2023-08-01 10:14 UTC
**Required System information**
    "@localazy/strapi-plugin": "^0.1.9",
    "@strapi/strapi": "4.10.5",
    
![image](https://github.com/localazy/strapi-plugin/assets/23020643/22981ab4-a6d9-41a6-88fd-8fa3e53cd1a4)
![image](https://github.com/localazy/strapi-plugin/assets/23020643/c5a66a37-d7bb-4952-a36f-1f4262e2dc8e)
![image](https://github.com/localazy/strapi-plugin/assets/23020643/4b4a28b8-ca7f-4ba0-abe1-edbe293a4f30)

**Comment by honzabilek4** [comment] 2023-08-01 12:30
Could you please describe what exactly is going on here?

**Comment by kingkong0828** [comment] 2023-08-07 02:57
> Could you please describe what exactly is going on here?

When I used the localazy plugin to translate my COLLECTION TYPES, my numeric type fields could not be uploaded to localazy, and when I downloaded starpi from localazy, they were automatically filled with the default values I set instead of the LOCALAZY SOURCE values

**Comment by honzabilek4** [comment] 2023-08-08 15:09
@david-vaclavek do you have an idea what might be going on here?

**Comment by david-vaclavek** [comment] 2023-08-09 11:27
Hello @kingkong0828. If I understand correctly, this particular case is described in [Strapi: Download Translations](https://localazy.com/docs/strapi/strapi-download-translations#download-to-strapi) documentation section.

For several reasons, numbers are not intended to be transferred to Localazy. Therefore, I think this is the intended behavior.

<img width="782" alt="image" src="https://github.com/localazy/strapi-plugin/assets/49518842/85384f9f-9b7d-4a14-b096-31749445405a">

In case you think I misunderstood your case, please send us a video recording that clarifies the problem.
We'll then discuss the case further.

I'm closing the issue for now. If necessary, I'll reopen it after your reaction. Thank you.

**Closed by david-vaclavek** 2023-08-09 11:27 UTC
